#!/bin/bash
# Generate .env from environment variables for Laravel
cat > /home/runner/workspace/.env << EOF
APP_NAME="${APP_NAME:-Mahalo Immobilier}"
APP_ENV=${APP_ENV:-local}
APP_DEBUG=${APP_DEBUG:-true}
APP_URL=${APP_URL:-http://localhost:8000}
APP_KEY=${APP_KEY:-}

LOG_CHANNEL=${LOG_CHANNEL:-daily}
LOG_LEVEL=${LOG_LEVEL:-debug}

BROADCAST_DRIVER=${BROADCAST_DRIVER:-log}
CACHE_STORE=${CACHE_STORE:-file}
QUEUE_CONNECTION=${QUEUE_CONNECTION:-sync}
SESSION_DRIVER=${SESSION_DRIVER:-file}
SESSION_LIFETIME=${SESSION_LIFETIME:-120}
SESSION_HTTP_ONLY=${SESSION_HTTP_ONLY:-true}
SESSION_SECURE_COOKIE=${SESSION_SECURE_COOKIE:-false}
ENABLE_HTTP_SECURITY_HEADERS=${ENABLE_HTTP_SECURITY_HEADERS:-false}

DB_CONNECTION=${DB_CONNECTION:-sqlite}
DB_DATABASE=${DB_DATABASE:-/home/runner/workspace/database/database.sqlite}
DB_STRICT=${DB_STRICT:-false}

ADMIN_DIR=${ADMIN_DIR:-admin}
CMS_ENABLE_INSTALLER=${CMS_ENABLE_INSTALLER:-false}

SANCTUM_STATEFUL_DOMAINS="${SANCTUM_STATEFUL_DOMAINS:-localhost:5000,localhost:8000}"

FRONTEND_URL=${FRONTEND_URL:-http://localhost:5000}
FRONTEND_PUBLIC_PATH=${FRONTEND_PUBLIC_PATH:-/home/runner/workspace/frontend/public}

FORCE_SCHEMA=${FORCE_SCHEMA:-http}
FORCE_ROOT_URL=${FORCE_ROOT_URL:-http://localhost:8000}

MAIL_MAILER=${MAIL_MAILER:-log}
MAIL_HOST=${MAIL_HOST:-smtp.hostinger.com}
MAIL_PORT=${MAIL_PORT:-465}
MAIL_USERNAME=${MAIL_USERNAME:-}
MAIL_ENCRYPTION=${MAIL_ENCRYPTION:-ssl}
MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS:-noreply@local.dev}
MAIL_FROM_NAME="${MAIL_FROM_NAME:-Mahalo Immobilier}"

GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:-}
GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET:-}
GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI:-http://localhost:8000/api/v1/auth/google/callback}
EOF
echo ".env generated"
